name: run openweathermap/APIToMongoDB.py

on:
  schedule:
    - cron: '20 13 * * 1,3,5' # At 14:00 on Monday, Wednesday, and Friday.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run APIToMongoDB.py
        env:
          REMOTE_DB_URL: ${{ secrets.REMOTE_DB_URL }}
          OPEN_WEATHER_MAP_API: ${{ secrets.OPEN_WEATHER_MAP_API }}
        run: python openweathermap/APIToMongoDB.py
          
#       - name: commit files
#         run: |
#           git config --local user.email "action@github.com"
#           git config --local user.name "GitHub Action"
#           git add -A
#           git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
#       - name: push changes
#         uses: ad-m/github-push-action@v0.6.0
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           branch: main 
